### ISSUE TITLE
Null reference error if target is in an invalid cell

### ISSUE THREAD

**Issue by sandsalamand** [matthiaszarzecki/AStarPathfindingUnity#1]
To reproduce: drag an obstacle so that the target is contained inside a red cell.

Log:
NullReferenceException: Object reference not set to an instance of an object
Grid+<CalculatePath>d__14.MoveNext () (at Assets/Scripts/Grid.cs:115)

**Comment by matthiaszarzecki** [comment]
Thanks for finding and reporting this! :) I finally got around to looking into it, and fixed that potential issue. I also updated the project to work with Unity 2021, and fixed some other stuff too.
